name: Deploy Application

on:
  push:
    branches: [ "dummy" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Execute deployment script
      run: |
          cd /home/ec2-user/aws-practice/cicdpractice
          chmod +x deploy.sh
          ./deploy.sh
